
package Vista;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import Controlador.SolicitudControlador;
import Modelo.Solicitud;
import Modelo.Cliente;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import Conection.ConectionMysql;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class solicitudes_en_el_hotel extends javax.swing.JFrame {

    /**
     * Creates new form solicitudes_en_el_hotel
     */
    private SolicitudControlador solicitudControlador;
    private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    public solicitudes_en_el_hotel() {
        initComponents();
        setLocationRelativeTo(null);
    }
   
    
    private void guardarSolicitudEnBD(SolicitudControlador controlador) {
    Connection cn = null;
    try {
        // Conexión a la base de datos
        ConectionMysql con = new ConectionMysql();
        cn = con.conectar();

        // Preparar la consulta SQL
        String sql = "INSERT INTO solicitudes (tipo_solicitud, nombre_cliente, numero_habitacion, descripcion, fecha_solicitud, estado) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = cn.prepareStatement(sql);
        
        // Establecer los valores
        pst.setString(1, controlador.getTipoSolicitud());
        pst.setString(2, controlador.getNombreCliente());
        pst.setString(3, controlador.getNumeroHabitacion());
        pst.setString(4, controlador.getDescripcion());
        pst.setDate(5, new java.sql.Date(controlador.getFechaSolicitud().getTime()));
        pst.setString(6, controlador.getEstado());

        // Ejecutar la consulta
        pst.executeUpdate();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al guardar la solicitud en la base de datos: " + e.getMessage());
    } finally {
        
        if (cn != null) {
            try {
                cn.close();
            } catch (Exception e) {
                
                JOptionPane.showMessageDialog(this, "Error al cerrar la conexión a la base de datos: " + e.getMessage());
            }
        }
    }
    }
    private void limpiarCampos() {
    ComboLimpieza.setSelectedIndex(0); 
    NumeroHabitacion.setText(""); 
    RecomendacionesTxt.setText(""); 
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ComboLimpieza = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NumeroHabitacion = new javax.swing.JTextField();
        RecomendacionesTxt = new javax.swing.JTextField();
        EnviarSolicitud = new javax.swing.JButton();
        InicioHomeee = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setName("solicitudes"); // NOI18N

        ComboLimpieza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Limpieza", "Mantenimiento", "Recepcion", "Solucion de problemas de seguridad", " " }));
        ComboLimpieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboLimpiezaActionPerformed(evt);
            }
        });

        jLabel2.setText("Que tipo de solicitud desea?");

        jLabel3.setText("Numero De Habitacion:");

        jLabel4.setText("recomendaciones:");

        NumeroHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroHabitacionActionPerformed(evt);
            }
        });

        RecomendacionesTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecomendacionesTxtActionPerformed(evt);
            }
        });

        EnviarSolicitud.setText("Enviar Solicitud");
        EnviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarSolicitudActionPerformed(evt);
            }
        });

        InicioHomeee.setText("Volver al Inicio");
        InicioHomeee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioHomeeeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(10, 10, 10))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnviarSolicitud)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboLimpieza, 0, 0, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RecomendacionesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(InicioHomeee)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboLimpieza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NumeroHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RecomendacionesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnviarSolicitud)
                    .addComponent(InicioHomeee))
                .addGap(49, 49, 49))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setName(""); // NOI18N

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("SOLICITUDES");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleName("");
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumeroHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroHabitacionActionPerformed
       
    }//GEN-LAST:event_NumeroHabitacionActionPerformed

    private void ComboLimpiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboLimpiezaActionPerformed
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_ComboLimpiezaActionPerformed

    private void RecomendacionesTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecomendacionesTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RecomendacionesTxtActionPerformed

    private void EnviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarSolicitudActionPerformed
        // TODO add your handling code here:
        try {
        // Obtener datos del formulario
        String tipoSolicitud = ComboLimpieza.getSelectedItem().toString();
        String numeroHabitacion = NumeroHabitacion.getText();
        String recomendaciones = RecomendacionesTxt.getText();
        Date fechaSolicitud = new Date(); // Usar la fecha actual
        String estado = "Pendiente"; // Establecer un estado por defecto
        String nombreCliente = "Nombre del Cliente"; // Debes obtener este dato desde el formulario si tienes el campo

        // Crear objeto Solicitud
        Solicitud solicitud = new Solicitud(tipoSolicitud, nombreCliente, numeroHabitacion, recomendaciones, fechaSolicitud, estado);

        
        SolicitudControlador controlador = new SolicitudControlador(solicitud);
        guardarSolicitudEnBD(controlador);

     
        JOptionPane.showMessageDialog(this, "Solicitud enviada correctamente.");
        
       
        limpiarCampos();
        } catch (Exception e) {
      
        JOptionPane.showMessageDialog(this, "Error al enviar la solicitud: " + e.getMessage());
        }
    }//GEN-LAST:event_EnviarSolicitudActionPerformed

    private void InicioHomeeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioHomeeeActionPerformed
        // TODO add your handling code here:
        InicioHome n1 = new InicioHome();
        n1.setVisible(true);
        n1.setLocationRelativeTo(null); // Centrar la nueva ventana en la pantalla
        this.dispose();
    }//GEN-LAST:event_InicioHomeeeActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboLimpieza;
    private javax.swing.JButton EnviarSolicitud;
    private javax.swing.JButton InicioHomeee;
    private javax.swing.JTextField NumeroHabitacion;
    private javax.swing.JTextField RecomendacionesTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    
  
}

